### ISSUE TITLE
OwlCarousel2 for rails Autoplay not working

### ISSUE THREAD

**Issue by sureshvaavel** [acrogenesis/owlcarousel-rails#7]
Hi,

Autoplay is not working with Owl-Carousel2

**Comment by acrogenesis** [comment]
I just updated the branch with the latest files from Owl-Carousel2. Please check it out

**Comment by sureshvaavel** [comment]
Still autoplay issue is there . it not autoplaying. Can  you check it please

**Comment by acrogenesis** [comment]
Please check on the developers github Issues https://github.com/smashingboxes/OwlCarousel2/issues

**Comment by eds123** [comment]
For anyone still encountering this issue.

The auto play functionality has it's own js file so you need to include "owl.autoplay" in your application.js

`//= require owl.autoplay`

It's also worth noting that Owl Carousel 2 uses `autoplay: true` instead of `autoPlay: true`

**Comment by bruce-hansen** [comment]
//= require owlcarousel2/owl.autoplay
